### ISSUE TITLE
chromedriver erro

### ISSUE THREAD

**Issue by feint9** [Macmod/TrailScraper#1]
Hi,

Build: Kali Linux latest build full update - amd64

NameScraper: latest from git, all requirements install
SecurityTrails cookie saved in session file

Error:

python namescraper.py --query google.com securitytrails  54s 
[+] Selected module: "SecurityTrails"
Traceback (most recent call last):
  File "/root/tools/NameScraper/namescraper.py", line 98, in <module>
    driver = uc.Chrome(use_subprocess=True, options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/undetected_chromedriver/__init__.py", line 441, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.11/dist-packages/undetected_chromedriver/__init__.py", line 704, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:56515
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 119.0.6045.105
Stacktrace:
#0 0x5556929d44e3 <unknown>
#1 0x555692703c76 <unknown>
#2 0x55569273104a <unknown>
#3 0x555692728884 <unknown>
#4 0x555692767ccc <unknown>
#5 0x55569276747f <unknown>
#6 0x55569275ede3 <unknown>
#7 0x5556927342dd <unknown>
#8 0x55569273534e <unknown>
#9 0x5556929943e4 <unknown>
#10 0x5556929983d7 <unknown>
#11 0x5556929a2b20 <unknown>
#12 0x555692999023 <unknown>
#13 0x5556929671aa <unknown>
#14 0x5556929bd6b8 <unknown>
#15 0x5556929bd847 <unknown>
#16 0x5556929cd243 <unknown>
#17 0x7ff19b4cd3ec <unknown>

**Comment by Macmod** [comment]
Indeed the `selenium` & `undetected-chromedriver`'s versions were outdated in the `requirements.txt`. It should be fixed in [6c56522](https://github.com/Macmod/NameScraper/commit/6c56522ae73ff9464724d10f477b87278d67d529).
